### PR TITLE
added repr methods to base home class[Issue #21]

### PR DESCRIPTION
**Pull request by muddi900**
#21

For the sake of testing, I have added `__str__` and `__repr__` a single class. Please do see if they work

### CODE REVIEW

**Comment by BeatsuDev** [comment]
Codecov bot is a bit strict... I should look into it's settings... But anyway, thanks for the contribution! My internet is currently down so I won't be able to check this PR on my computer just yet, but once I've just checked how it looks I'll comment here again or merge it. Great work! 😄

**Comment by muddi900** [comment]
Thanks

**Comment by BeatsuDev** [comment]
Hi, I tested it on the demo account now and here is the output:
```
Vitahuset is owned by <tibber.types.legal_entity.LegalEntity object at 0x000002138E79EE90> with 5 residents at None 
```

Could you make it display the name of the owner instead? Maybe you could also add a check to see if the city is defined before adding it to the string? Otherwise, it looks good!

**Comment by BeatsuDev** [comment]
Nice! Just a last little change; it would be great if you could use double quotes instead of single quotes just to stay consistent with the rest of the project 😄

**Pull request merged**
